### ISSUE TITLE
Excessive Permissions / Configurations for Exchange Online?

### ISSUE THREAD

**Issue by Mike-Crowley** [osTicket/docs#149]
Hi @JediKev, can you clarify a few things on the Microsoft Email Authorization Guide? I'm trying to support an environment with this software but am not understanding how this works

- https://docs.osticket.com/en/latest/OAuth2/Microsoft%20Authorization%20Guide.html
- https://github.com/osTicket/docs/blob/master/OAuth2/Microsoft%20Authorization%20Guide.rst

1. The product prompts for "read and WRITE" access to user mail, but this isn't listed in your guide
2. The product seems to use delegated permissions, so why is a client secret also needed? Where are you logging in AS the app?
3. Why are both POP and also IMAP permissions needed? Are these not mutually exclusive?
4. Why is Microsoft Graph mailbox even being requested at all, if this is using IMAP (or POP)?

**Comment by Mike-Crowley** [comment]
I see. Thank you for the super fast response! If you'd like to collaborate on this, I'd be happy to chat offline. I don't know the OSTicket product, but could possibly help tighten up the Microsoft Graph side of things.

**Comment by JediKev** [comment]
@Mike-Crowley 

Thank you for the offer. We will definitely reach out if we need assistance.

Cheers.
