### ISSUE TITLE
Failing to complete the OAuth install

### ISSUE THREAD

**Issue by ElbowNi** [osTicket/docs#150]
Nice document but having got all the way though to authorising the MS api which I do
![image](https://user-images.githubusercontent.com/8257991/197215160-b47127b3-e8f6-4bf5-a630-a5e478e595fe.png)
, it then fails to redirect me to the "Completed (green tick)" page in OSticket
![image](https://user-images.githubusercontent.com/8257991/197214243-fe03786e-fd8c-4974-93d0-5301e3ea5e22.png) with the Not Found page
Any ideas why this is not

**Comment by JediKev** [comment]
@ElbowNi 

Please make a post on [our Forum](https://forum.osticket.com) instead. URL Rewriting is not enabled on your webserver. This is not an osTicket issue.

Cheers.

**Comment by ElbowNi** [comment]
Love you @JediKev, added the URL Rewrite and all good!
