### ISSUE TITLE
microsoft oauth2 configuration using Microsoft Office 365 essential via godaddy

### ISSUE THREAD

**Issue by Niba-nazar** [osTicket/docs#151]
hi,

I have found the oauth2 configuration with azure, likewise is there any possibility to configure oauth2 using Microsoft Office 365 essential via GoDaddy??

https://github.com/osTicket/docs/blob/3b6b623c026c15bb267e404a4afd72b19d29f035/OAuth2/Microsoft%20Authorization%20Guide.rst

**Comment by JediKev** [comment]
@Niba-nazar 

If their MS O365 service isn't like the documentation then you'd have to reach out to GoDaddy and ask them for their specific documentation on OAuth2 setup for email authentication. We only have documentation for MS O365 and Google at this time; however any provider should work (as long as they follow the norms/standards).

Also, this question is best suited for [our Forum here](https://forum.osticket.com). Next time you have a question, please post there instead.

Cheers.
