### ISSUE TITLE
Office 365 email issues

### ISSUE THREAD

**Issue by JanosTurk** [osTicket/docs#154]
I'm really interested in how the http://localhost:8199/php81/osticket/api/auth/oauth2 link should work externally... 
I have tried to change the localhost to the VM domain name but still not working. 
I have done all steps one by one the result is: 

![image](https://user-images.githubusercontent.com/114268701/206469358-6aa26cec-328c-4c05-bc49-a6c1a4dee7ee.png)

under the email settings. 
If I try to login to the portal using the Azure login the website breaks with the following error message. 
![image](https://user-images.githubusercontent.com/114268701/206469879-a19612c1-e25b-4cc6-933c-81f3b0281b38.png)
I'm not surprised as the localhost redirect URL is 100% wrong.

**Comment by JediKev** [comment]
@JanosTurk 

Please use [our Forum](https://forum.osticket.com) for discussions like these.

Cheers.
