### ISSUE TITLE
Doesn't work on v1.17.2

### ISSUE THREAD

**Issue by ThePaulius** [osTicket/docs#157]
```
php manage.php file migrate --backend D --to F
php manage.php --help
```

The server team also tried running it, and nothing happened.

osTicket Version | v1.17.2 (8fbc7ee)     —  Up to date
Web Server Software | Apache
MySQL Version | 5.7.41
PHP Version | 8.0.28

**Comment by JediKev** [comment]
@ThePaulius 

1. Wrong repo; this is for docs only.
2. GitHub is not a support Forum. Any questions/issues need to be posted on our [Forum](https://forum.osticket.com).

Cheers.
