### ISSUE TITLE
issue with php with new version

### ISSUE THREAD

**Issue by sabahsawor** [osTicket/docs#174]
Hi All,

I have issue when try to upgrade from osticket from version 1.17.5 to 1.18.1 but after moved the new version files to the system I get this message 
`Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.1.0".`
I removed disabled all old php version 7.4 and 8.0, and restart Nginx but no luck.
Hoe to point osticket to latest version of php.

this is the list of php installed 
```
root@helpdesk:~# sudo update-alternatives --config php
There are 3 choices for the alternative php (providing /usr/bin/php).

  Selection    Path             Priority   Status
------------------------------------------------------------
* 0            /usr/bin/php8.2   82        auto mode
  1            /usr/bin/php7.4   74        manual mode
  2            /usr/bin/php8.0   80        manual mode
  3            /usr/bin/php8.2   82        manual mode
```

**Comment by JediKev** [comment]
@sabahsawor 

This is the docs repo; not the core repo. The core repo is here:
- https://github.com/osTicket/osTicket

With this being said, your post is more of a question/setup issue; not a bug, feature request, or pull request. Questions/setup issues are best suited for our [Community Supported Forum](https://forum.osticket.com).

Cheers.

**Comment by sabahsawor** [comment]
> @sabahsawor
> 
> This is the docs repo; not the core repo. The core repo is here:
> 
> * https://github.com/osTicket/osTicket
> 
> With this being said, your post is more of a question/setup issue; not a bug, feature request, or pull request. Questions/setup issues are best suited for our [Community Supported Forum](https://forum.osticket.com).
> 
> Cheers.

I just fix the issue, this is a bug in the system 
under the file path 
/srv/osticket/upload/include/laminasmail/vendor/composer/platform_check.php

you guys need to replace `if (!(PHP_VERSION_ID >= 80100))`
with line `if (!(PHP_VERSION_ID <= 80100)) `

so the composer dosn't through the error I mentioned
