### ISSUE TITLE
Department visibility restrictions can be overridden in canned responses.

### ISSUE THREAD

**Issue by ml247** [osTicket/docs#178]
When viewing the list of canned responses at /scp/canned.php you will NOT see any canned responses that are in a department to which you have no access.

However you CAN still see such canned responses directly by entering the canned response ID number into the URL. E.g.:
/scp/canned.php?id=11

If I did not have departmental access to canned response 11, I will still be able to view it by entering the URL above.

This is in version 1.18.1

**Comment by JediKev** [comment]
@ml247 

My apologies I should’ve clarified the repo to use. This is the wrong repo; this is for the Documentation site. You are looking for the [core repo here](https://github.com/osTicket/osTicket).

Cheers.
