### ISSUE TITLE
Queue Tab Missing on Settings and Option on v1.10.1 (9ae093d)

### ISSUE THREAD

**Issue by Marcovus** [osTicket/docs#42]
I can´t find the Queue Tab to add a costom queue inside my Admin panel, see the picture. 
![grafik](https://user-images.githubusercontent.com/16650801/56283711-cdb4e200-6112-11e9-9e5a-139dc07de9ca.png)

**Comment by JediKev** [comment]
@Marcovus 

You have to use the latest stable release of v1.11 to see Custom Queues feature.

Cheers.

**Comment by Marcovus** [comment]
Thanks, I´m using it on Synology and it showed me that this is the latest release (but as it seams it is the latest releas for Synology) So I wait until Synology will have an update!
Sorry for reporting an issue that is none.
