### ISSUE TITLE
Error - 404 - docs/downloads/pdf/latest/

### ISSUE THREAD

**Issue by mlipok** [osTicket/docs#63]
I wanted to read documentation from here:
https://docs.osticket.com/en/latest/
as a EPUB or PDF

Using this option:
![osTicket_Doc_Issue1_v1](https://user-images.githubusercontent.com/11089482/63366212-84eb8f00-c379-11e9-8512-a563bfe26d16.jpg)

When I trying to get PDF (but also EPUB) I get this kind of error:
![osTicket_Doc_Issue1_v2](https://user-images.githubusercontent.com/11089482/63366211-84eb8f00-c379-11e9-83fb-ba4453aa0b59.jpg)

**Comment by JediKev** [comment]
@mlipok 

Just type `http://` in front of the domain and it will work. We are looking into the SSL issue so please bear with us.

Cheers.

**Comment by mlipok** [comment]
Thanks.
Your suggestion works as a workaround.

**Comment by mlipok** [comment]
Checked on "Moon+ Reader" on Android - this EPUB version is fine, just MS Edge have some problems.

**Comment by JediKev** [comment]
This has been resolved.
