### ISSUE TITLE
Change Log out of date

### ISSUE THREAD

**Issue by ntozier** [osTicket/docs#69]
When you upgrade osTicket to a new version you see the "Upgrade Completed!" page.  This is good.  

It looks like this:
![2019-12-05_1218](https://user-images.githubusercontent.com/1315768/70258173-bc7c1c80-1759-11ea-9750-654c8c9f92ac.png)

The Release Notes link points to:
`https://docs.osticket.com/en/latest/Developer%20Documentation/Changelog.html?highlight=notes`

This is good and fine, but that page shows the change log for 1.12.2.  
Not the latest version(s) which is 1.14.1 as of this issue being opened.

**Comment by JediKev** [comment]
@ntozier 

Thank you. Yes I’ve been meaning to update that. It should really link to release notes on GitHub as I think we are going to discontinue that on the docs site. I will get clarification and update it. Will post update here.

Cheers.

**Comment by ntozier** [comment]
Sounds good.  Do you want me to close this or leave it open to remind you?

**Comment by JediKev** [comment]
@ntozier 

Leave it open, I tend to forget things 😉 

Cheers.

**Comment by JediKev** [comment]
@ntozier This ought to do it:
- https://github.com/osTicket/docs/pull/71
